#!/usr/bin/env node
/**
 * Eventide Omega one-file Node.js panel installer + launcher.
 *
 * Upload this file to the panel home folder and use:
 *   node panel-install.js
 *
 * Optional panel variables:
 *   APP_DIR=/home/container/eventide-omega-bug-test
 *   REPO_URL=https://github.com/Phantom-Dev-X/eventide-omega-bug-test.git
 *   REPO_BRANCH=main
 */

// This installer is intentionally CommonJS so a panel can run the standalone
// uploaded file directly, without package.json or Bash.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawn, spawnSync } = require('node:child_process');

const REPO_URL = process.env.REPO_URL || 'https://github.com/Phantom-Dev-X/eventide-omega-bug-test.git';
const REPO_BRANCH = process.env.REPO_BRANCH || 'main';
const scriptDir = path.dirname(path.resolve(process.argv[1] || 'panel-install.js'));
const scriptIsInsideRepo = fs.existsSync(path.join(scriptDir, 'package.json'))
    && fs.existsSync(path.join(scriptDir, 'index.js'));
const APP_DIR = path.resolve(process.env.APP_DIR || (
    scriptIsInsideRepo ? scriptDir : path.join(process.cwd(), 'eventide-omega-bug-test')
));

function say(message) {
    console.log(`\n[PANEL-INSTALL] ${message}`);
}

function die(message, error = null) {
    console.error(`\n[PANEL-INSTALL] ERROR: ${message}`);
    if (error?.message) console.error(`[PANEL-INSTALL] ${error.message}`);
    process.exit(1);
}

function run(command, args, options = {}) {
    const result = spawnSync(command, args, {
        cwd: options.cwd || process.cwd(),
        env: { ...process.env, GIT_TERMINAL_PROMPT: '0' },
        stdio: options.capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
        encoding: 'utf8'
    });
    if (result.error) throw result.error;
    if (result.status !== 0) {
        const detail = options.capture ? String(result.stderr || result.stdout || '').trim() : '';
        throw new Error(`${command} ${args.join(' ')} failed with exit code ${result.status}${detail ? `: ${detail}` : ''}`);
    }
    return options.capture ? String(result.stdout || '').trim() : '';
}

function commandExists(command) {
    const probe = spawnSync(command, ['--version'], { stdio: 'ignore' });
    return !probe.error && probe.status === 0;
}

function directoryHasFiles(directory) {
    try {
        return fs.existsSync(directory) && fs.readdirSync(directory).length > 0;
    } catch {
        return false;
    }
}

const nodeMajor = Number(process.versions.node.split('.')[0]);
if (nodeMajor < 20) {
    die(`Node.js 20+ is required by xzcbailz. Found ${process.version}. Select a Node 20 or 22 panel image.`);
}
if (!commandExists('git')) die('git is not installed in this panel image.');
if (!commandExists('npm')) die('npm is not installed in this panel image.');

say(`Repository: ${REPO_URL}`);
say(`Branch:     ${REPO_BRANCH}`);
say(`App folder: ${APP_DIR}`);

try {
    if (fs.existsSync(path.join(APP_DIR, '.git'))) {
        say('Existing checkout found; fetching the latest commit...');
        try { run('git', ['config', '--global', '--add', 'safe.directory', APP_DIR]); } catch {}
        run('git', ['remote', 'set-url', 'origin', REPO_URL], { cwd: APP_DIR });
        run('git', ['fetch', '--depth', '1', 'origin', REPO_BRANCH], { cwd: APP_DIR });
        run('git', ['checkout', '-f', '-B', REPO_BRANCH, `origin/${REPO_BRANCH}`], { cwd: APP_DIR });
    } else if (directoryHasFiles(APP_DIR)) {
        die(`${APP_DIR} exists and is not an empty Git checkout. Set APP_DIR to an empty folder.`);
    } else {
        say('Cloning Eventide Omega...');
        fs.mkdirSync(path.dirname(APP_DIR), { recursive: true });
        fs.rmSync(APP_DIR, { recursive: true, force: true });
        run('git', ['clone', '--depth', '1', '--branch', REPO_BRANCH, REPO_URL, APP_DIR]);
    }
} catch (error) {
    die('Could not clone/update the repository.', error);
}

const envPath = path.join(APP_DIR, '.env');
if (!fs.existsSync(envPath)) {
    say(`Creating ${envPath} (fill the blank values later, then restart)...`);
    const envTemplate = `# EVENTIDE OMEGA — PANEL ENVIRONMENT
# Generated by panel-install.js. Panel variables override values in this file.

# Required: permit WhatsApp sockets outside Render.
PANEL_BOT_ENABLED=true

# Required on a panel: persistent local disk, no Supabase synchronization.
USE_SUPABASE=false
SUPABASE_URL=
SUPABASE_KEY=

# Git updates on panel restart and through .gitpull.
AUTO_UPDATE=true
GIT_REMOTE_URL=https://github.com/Phantom-Dev-X/eventide-omega-bug-test.git

# Leave PORT blank when the panel injects SERVER_PORT automatically.
PORT=
MAX_USERS=10
VERBOSE_LOGS=false

# Optional Telegram pairing/admin bot.
TELEGRAM_TOKEN=
DEV_TELEGRAM_IDS=
TELEGRAM_BACKUP_CHANNEL=

# WhatsApp developer numbers: digits only, comma-separated, no plus sign.
DEV_NUMBERS=

# Optional AI providers.
GEMINI_API_KEY=
GEMINI_MODEL=gemini-2.0-flash
OPENAI_API_KEY=

# Optional website/channel settings.
GROUP_CHANNEL_LINK=
ALLOWED_ORIGINS=

# Local backups.
BACKUP_EVERY_MIN=360
BACKUP_KEEP=7

# Reconnection tuning.
CLOSE428_DELAY_MS=15000
CLOSE428_STORM_BACKOFF_MS=60000
`;
    fs.writeFileSync(envPath, envTemplate, { encoding: 'utf8', mode: 0o600 });
} else {
    say('Existing .env found; keeping your values unchanged.');
}

fs.mkdirSync(path.join(APP_DIR, 'sessions'), { recursive: true });
fs.mkdirSync(path.join(APP_DIR, 'backups'), { recursive: true });

const packagePath = path.join(APP_DIR, 'package.json');
const packageHash = crypto.createHash('sha256').update(fs.readFileSync(packagePath)).digest('hex');
const hashFile = path.join(APP_DIR, '.panel-package.sha256');
const oldHash = fs.existsSync(hashFile) ? fs.readFileSync(hashFile, 'utf8').trim() : '';
const dependenciesMissing = !fs.existsSync(path.join(APP_DIR, 'node_modules', 'xzcbailz', 'package.json'));

if (dependenciesMissing || oldHash !== packageHash) {
    say('Installing production dependencies...');
    try {
        run('npm', ['install', '--omit=dev', '--no-audit', '--no-fund', '--allow-git=all'], { cwd: APP_DIR });
        fs.writeFileSync(hashFile, packageHash, 'utf8');
    } catch (error) {
        die('Dependency installation failed.', error);
    }
} else {
    say('Dependencies are already current.');
}

let commit = 'unknown commit';
try {
    commit = run('git', ['log', '-1', '--oneline'], { cwd: APP_DIR, capture: true });
} catch {}

say(`Running commit: ${commit}`);
say('Starting Eventide Omega with boot.js...');
say('Warning: do not run the same paired WhatsApp session on Render and this panel simultaneously.');

const child = spawn(process.execPath, ['boot.js'], {
    cwd: APP_DIR,
    env: process.env,
    stdio: 'inherit'
});

let forwardingSignal = false;
for (const signal of ['SIGTERM', 'SIGINT']) {
    process.on(signal, () => {
        if (forwardingSignal) return;
        forwardingSignal = true;
        say(`${signal} received; forwarding it to boot.js...`);
        if (!child.killed) child.kill(signal);
        setTimeout(() => process.exit(0), 5000).unref();
    });
}

child.on('error', error => die('Could not start boot.js.', error));
child.on('exit', (code, signal) => {
    if (signal) {
        say(`boot.js exited from ${signal}.`);
        process.exit(0);
    }
    process.exit(Number.isInteger(code) ? code : 1);
});
