#!/usr/bin/env bash
# Eventide Omega one-file panel installer + launcher.
#
# Upload this file to your panel and use this startup command:
#   bash panel-install.sh
#
# Optional panel variables:
#   APP_DIR=/home/container/eventide-omega-bug-test
#   REPO_URL=https://github.com/Phantom-Dev-X/eventide-omega-bug-test.git
#   REPO_BRANCH=main

set -Eeuo pipefail

REPO_URL="${REPO_URL:-https://github.com/Phantom-Dev-X/eventide-omega-bug-test.git}"
REPO_BRANCH="${REPO_BRANCH:-main}"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# If the script is already inside a checkout, use that checkout. If it was
# uploaded by itself to the panel root, clone into a child app directory.
if [[ -f "$SCRIPT_DIR/package.json" && -f "$SCRIPT_DIR/index.js" ]]; then
    APP_DIR="${APP_DIR:-$SCRIPT_DIR}"
else
    APP_DIR="${APP_DIR:-$PWD/eventide-omega-bug-test}"
fi

say() { printf '\n[PANEL-INSTALL] %s\n' "$*"; }
die() { printf '\n[PANEL-INSTALL] ERROR: %s\n' "$*" >&2; exit 1; }

command -v git >/dev/null 2>&1 || die "git is not installed in this panel image."
command -v node >/dev/null 2>&1 || die "Node.js is not installed in this panel image."
command -v npm >/dev/null 2>&1 || die "npm is not installed in this panel image."

NODE_MAJOR="$(node -p "Number(process.versions.node.split('.')[0])")"
if (( NODE_MAJOR < 20 )); then
    die "Node.js 20+ is required by xzcbailz. Found $(node -v). Select a Node 20 or 22 panel image."
fi

say "Repository: $REPO_URL"
say "Branch:     $REPO_BRANCH"
say "App folder: $APP_DIR"

if [[ -d "$APP_DIR/.git" ]]; then
    say "Existing checkout found; fetching the latest commit..."
    git config --global --add safe.directory "$APP_DIR" >/dev/null 2>&1 || true
    git -C "$APP_DIR" remote set-url origin "$REPO_URL"
    git -C "$APP_DIR" fetch --depth 1 origin "$REPO_BRANCH"
    git -C "$APP_DIR" checkout -f -B "$REPO_BRANCH" "origin/$REPO_BRANCH"
elif [[ -e "$APP_DIR" && -n "$(find "$APP_DIR" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)" ]]; then
    die "$APP_DIR exists and is not an empty Git checkout. Set APP_DIR to an empty folder."
else
    say "Cloning Eventide Omega..."
    mkdir -p "$(dirname "$APP_DIR")"
    rm -rf "$APP_DIR"
    git clone --depth 1 --branch "$REPO_BRANCH" "$REPO_URL" "$APP_DIR"
fi

cd "$APP_DIR"

# Create the panel environment once. Never overwrite it on later starts, so
# values entered by the owner survive restarts and git updates.
if [[ ! -f .env ]]; then
    say "Creating $APP_DIR/.env (blank secrets can be filled in later)..."
    cat > .env <<'ENVFILE'
# ─────────────────────────────────────────────────────────────────────────────
# EVENTIDE OMEGA — PANEL ENVIRONMENT
# Generated by panel-install.sh. Edit the blank values, then restart the server.
# Values configured by the panel itself take priority over this file.
# ─────────────────────────────────────────────────────────────────────────────

# REQUIRED: allows this Render-safe build to open WhatsApp sockets on a panel.
PANEL_BOT_ENABLED=true

# REQUIRED FOR PANEL: local persistent disk; no Supabase cloud synchronization.
USE_SUPABASE=false
SUPABASE_URL=
SUPABASE_KEY=

# Pull the latest GitHub main commit whenever the panel starts.
AUTO_UPDATE=true
GIT_REMOTE_URL=https://github.com/Phantom-Dev-X/eventide-omega-bug-test.git

# Leave PORT blank when Pterodactyl injects SERVER_PORT automatically.
# Otherwise enter your allocated panel port here, for example PORT=3000.
PORT=
MAX_USERS=10
VERBOSE_LOGS=false

# Telegram pairing/admin bot (optional; leave blank if using web pairing only).
TELEGRAM_TOKEN=
DEV_TELEGRAM_IDS=
TELEGRAM_BACKUP_CHANNEL=

# WhatsApp developer/owner numbers, digits only, comma-separated. No plus sign.
DEV_NUMBERS=

# Optional AI providers.
GEMINI_API_KEY=
GEMINI_MODEL=gemini-2.0-flash
OPENAI_API_KEY=

# Optional website/channel settings.
GROUP_CHANNEL_LINK=
ALLOWED_ORIGINS=

# Local automatic backups.
BACKUP_EVERY_MIN=360
BACKUP_KEEP=7

# Reconnection tuning. Defaults below are safe for most panels.
CLOSE428_DELAY_MS=15000
CLOSE428_STORM_BACKOFF_MS=60000
ENVFILE
    chmod 600 .env 2>/dev/null || true
else
    say "Existing .env found; keeping your values unchanged."
fi

mkdir -p sessions backups

# Install only when dependencies are absent or package.json has changed.
PACKAGE_HASH="$(node -e "const fs=require('fs'),c=require('crypto');process.stdout.write(c.createHash('sha256').update(fs.readFileSync('package.json')).digest('hex'))")"
OLD_HASH="$(cat .panel-package.sha256 2>/dev/null || true)"
if [[ ! -d node_modules || ! -f node_modules/xzcbailz/package.json || "$PACKAGE_HASH" != "$OLD_HASH" ]]; then
    say "Installing production dependencies..."
    npm install --omit=dev --no-audit --no-fund --allow-git=all
    printf '%s' "$PACKAGE_HASH" > .panel-package.sha256
else
    say "Dependencies are already current."
fi

say "Running commit: $(git log -1 --oneline)"
say "Starting Eventide Omega with the panel supervisor..."
say "Warning: do not run the same paired WhatsApp session on Render and this panel at the same time."

# exec keeps boot.js as the panel's main process so stop/restart signals work.
exec node boot.js
